di_platform_homepage:
    path:     /
    defaults: { _controller: DIPlatformBundle:Default:index }

di_platform_view:
    path:     /advert/{id}
    defaults: { _controller: DIPlatformBundle:Default:view }
    requirements:
        id: \d+

di_platform_edit:
    path:     /edit/{id}
    defaults: { _controller: DIPlatformBundle:Default:edit }
    requirements:
        id: \d+

di_platform_delete:
    path:     /delete/{id}
    defaults: { _controller: DIPlatformBundle:Default:delete }
    requirements:
        id: \d+

di_platform_add:
    path:     /add
    defaults: { _controller: DIPlatformBundle:Default:add }

toto:
    path:     /toto
    defaults: { _controller: DIPlatformBundle:Default:toto }

detailuser:
    path:     /detailuser/{id}
    defaults: { _controller: DIPlatformBundle:Default:detailuser }
    requirements:
            id: \d+