di_platform:
    resource: "@DIPlatformBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/platform
    requirements:
        _locale: en|fr

app:
    resource: '@AppBundle/Controller/'
    type: annotation
